### ISSUE TITLE
Failed to open Stream

### ISSUE THREAD

**Issue by tuami** [FriendsOfShopware/FroshWebP#10]
Hi we get this error after thumbnail generation via ssh. How can we solve that? Thank you in advance!

xxx:/home/www/xxx/html/shopware534/__test > php bin/console shyim:webp:download-google-binaries
xxx:/home/www/xxx/html/shopware534/__test > php bin/console sw:thumbnail:generate -f
Generating Thumbnails for Album Blog (ID: -11)
  0/19 [>---------------------------]   0%
Notice: Array to string conversion in /html/shopware534/__test/vendor/symfony/process/Process.php on line 281

Warning: file_get_contents(/tmp/cwebpOwqGQo-dst): failed to open stream: No such file or directory in /html/shopware534/__test/custom/plugins/ShyimWebP/Services/WebpEncoders/GoogleBinary.php on lin
e 44

**Comment by shyim** [comment]
Could you share some informations about your Setup?
Are you using a CDN or external storage like S3, Azure ?

**Comment by tuami** [comment]
No we´re not with a cdn provider. If we disable ShyimWebP thumbnail generation works normal.

**Comment by shyim** [comment]
I guess there is a execution error. Can you add here a debug
https://github.com/shyim/ShyimWebP/blob/master/Services/WebpEncoders/GoogleBinary.php#L43
with ->getOutput() to

**Comment by tuami** [comment]
The thumbnail generation in the console works (output), but eventually it breaks off. In the frontend the Webp images are not displayed, (Chrome of course)


Generating Thumbnails for Album 13 (ID: 258)
 0/4 [>---------------------------]   0%
 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
Generating Thumbnails for Album 14 (ID: 259)
 0/4 [>---------------------------]   0%
 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
Generating Thumbnails for Album 16 (ID: 261)
 0/4 [>---------------------------]   0%
 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
Generating Thumbnails for Album 17 (ID: 262)
 0/4 [>---------------------------]   0%
 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
Generating Thumbnails for Album static (ID: 263)
 0/4 [>---------------------------]   0%
 1/4 [=======>--------------------]  25%
 2/4 [==============>-------------]  50%
 3/4 [=====================>------]  75%
 4/4 [============================] 100%
Thumbnail generation finished with errors
Process must be started before calling getOutput.

**Comment by shyim** [comment]
Hey @tuami,
sorry for the late response. What happends if you dump getStatus?
Is proc_open allowed in php.ini?
