### ISSUE TITLE
Image element do not have src attributes

### ISSUE THREAD

**Issue by e-nitio** [FriendsOfShopware/FroshWebP#100]
Missing src-attribute in picture/image tag

Picture and image tags do not have explicit "src" attributes, only the srcset attributes are set.
This causes html validation error, which doesn't really matter that much. 
But implementing those attributes could actually improve browser backward compatibility by providing a valid fallback src attribute and in addition to that getting rid of the validation problem.

**Comment by shyim** [comment]
Hey,

can you provide an Pull request? 😅

**Comment by shyim** [comment]
Hey,

feel free to write when you want to work on it 😄
