### ISSUE TITLE
No WebP application on images built in shopping worlds and banners

### ISSUE THREAD

**Issue by markonelio** [FriendsOfShopware/FroshWebP#102]
### Question

Hello,

I installed the plugin but oddly only product pictures are getting loaded as WebP.

Images in digital publishing sliders or ones that are just built into shopping worlds as image-elements cannot be loaded as WebP. Is there something I can do, so every type of image gets loaded or is it a bug?

Thanks in advance!

**Comment by shyim** [comment]
It's not a general solution. It needs to be adjusted for each image tag. 
See as example https://github.com/FriendsOfShopware/FroshWebP/blob/master/Resources/views/frontend/checkout/ajax_add_article.tpl#L16-L27
