### ISSUE TITLE
Generate webp

### ISSUE THREAD

**Issue by AlbiWe** [FriendsOfShopware/FroshWebP#104]
### Question

Hallo,

es funktioniert
`php bin/console frosh:webp:status` => ok, grün
`php bin/console frosh:webp:download-google-binaries` => ok
`php bin/console sw:thumbnail:generate -f` => läuft durch
webp-Support ist aktiv

Das Generieren der webp-Bilder über
`/bin/console frosh:webp:generate` (PHP 7.4.26, --with-webp) bricht ab mit der Meldung ab:

`STACK: 426
OFFSET: 0
    0 [->--------------------------]`

Woran könnte das liegen?

Grüße
Albi

**Comment by Dieblich** [comment]
Der Fehler tritt bei mir auch auf. Ebenfalls mit PHP 7.4.26.

**Comment by Dwza** [comment]
habt ihr mal versucht statt `-f` den vollen wert `--force=true` anzugeben?

**Comment by Dieblich** [comment]
Hi @Dwza, 

danke erstmal für die Antwort. Mit

`frosh:webp:generate --force=true  `

läuft es bei mir wieder durch. **Vielen Dank** :+1: .

**Comment by Dwza** [comment]
Hi @Dieblich,
ich habe eine Änderung vorgenommen mit der es nun auch mit  `-f` und `--force` funktioniert, ohne den Parameter mitzugeben.

**Comment by Dieblich** [comment]
Danke @Dwza , ich nutze es seitdem am liebsten mit `-f`. Thumbs up :).

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/FroshWebP/releases/tag/1.1.5
