### ISSUE TITLE
WebP funktioniert nicht immer

### ISSUE THREAD

**Issue by catcologne-github** [FriendsOfShopware/FroshWebP#105]
### Question

Hallo,

wir haben das Plugin von WebP schon lange im Einsatz. Allerdings wird das WebP Bild in der Blog-Übersicht anzeigt, in der Artikel-Detail-Seite aber nicht. z.B. hier:
https://www.nutri-plus.de/blog/umwelt-tierschutz/
Detail-Seite:
https://www.nutri-plus.de/tierversuche-ueberfluessige-tradition
Auch bei den Produktbildern wird kein WebP angezeigt. 
Noch eine Frage:
Muss man die Konvertierung immer wieder machen (per Cron über Nacht z.B.)? Wir sind bei timmehosting, ich dachte da geht das automatisch?

Vielen Dank und viele Grüße,
Catarina.

**Comment by shyim** [comment]
Hey,

nur beim Klick auf das Bild kommt man auf das WebP Bild. Glaub, das ist nicht ganz so schlimm 🤔, alles andere scheint via WebP geladen zu werden
