### ISSUE TITLE
Einzelne Alben / Bilder generieren

### ISSUE THREAD

**Issue by Dieblich** [FriendsOfShopware/FroshWebP#109]
### Please describe the feature you would like to see implemented.

Hi, 

wenn wir im Shop (5.6.2, php 7.4) neue Bilder hochladen fände ich es klasse, wenn man nicht jedes Mal **alle** webp-Bilder mit `php bin/console sw:thumbnail:generate -f` neu generieren müsste. Das dauert z.B. bei uns immer länger als eine Stunde um eigentlich nur drei/vier neue Bilder zu erzeugen.

Als Lösung könnte ich mir folgendes vorstellen: 
1. Die SW merkt sich, wann sie zuletzt gelaufen ist. Wenn man die webp-Generierung mit z.B. `--new` startet, dann werden Quellbilder, deren Uploaddatum neue ist als der letzte Umwandlungslauf, in Webp umgewandelt. 
2. Man gibt einen Albumnamen mit `--album='Mein Album'`
3. Man gibt einen Filter mit für ein Startdatum, ab dem geschaut werden soll (z.B. --date=11-11-2022) oder `--max-upload-age=3` (days).

Über das Feature würden wir uns sehr freuen :).

PS: Danke für das tolle Plugin, es funktioniert soweit richtig gut.

**Comment by shyim** [comment]
Hey,

Wenn du neue Bilder höchlädst werden die schon optimiert. Ich bin nur noch aktiv an Shopware 6 am arbeiten, wenn du einen PR erstellst schau ich mir das gerne an

**Comment by shyim** [comment]
Albumn geht schon via --setCollection ID.
