### ISSUE TITLE
frosh:webp:generate doesn't work, but no error is shown

### ISSUE THREAD

**Issue by amargoShop** [FriendsOfShopware/FroshWebP#117]
### PHP Version

7.4

### Shopware Version

Shopware 5.7.11

### Actual behaviour

Using the command "frosh:webp:generate" via console, the webp pictures are not generated. 
The Console shows only the following and a prompt after.

STACK: 1637
OFFSET: 0
    0 [->--------------------------]

### Expected behaviour

the webp pictures should be generated and the console should count the images  

### Steps to Reproduce?

Using the command "frosh:webp:generate" via console

**Comment by shyim** [comment]
Hey,

This happens when the command skips existing files. You can use `-f` to force regeneration
