### ISSUE TITLE
Crash after Plugin Update

### ISSUE THREAD

**Issue by Marcel-Cologne** [FriendsOfShopware/FroshWebP#121]
### PHP Version

7.4

### Shopware Version

5.7.13

### Actual behaviour

Fatal error: Uncaught Error: Class 'FroshWebP\Subscriber\ModernizrSubscriber' not found in /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/engine/Shopware/Components/ContainerAwareEventManager.php:159 Stack trace: #0 /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/var/cache/production_202206221313/proxies/ShopwareProduction5e59d64c8ff1daaa0580f5112d553be23d4a1c4aProjectContainer.php(7354): Shopware\Components\ContainerAwareEventManager->addSubscriberService() #1 /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/vendor/symfony/dependency-injection/Container.php(257): ShopwareProduction5e59d64c8ff1daaa0580f5112d553be23d4a1c4aProjectContainer->getEventsService() #2 /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make() #3 /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/engine/Shopware/Components/DependencyInjection/Container.php(64): Symfony\Component\DependencyInjection\Container->get() #4 /var/www/kd/www.xxxxx.de/htdocs/shop in /var/www/kd/www.xxxxx.de/htdocs/shopware/dev/engine/Shopware/Components/ContainerAwareEventManager.php on line 159

### Expected behaviour

I expected an updated plugin ;-)

### Steps to Reproduce?

I simply clicked on the update button

**Comment by shyim** [comment]
looks like cache issue. can you clear the cache? 😅

**Comment by Marcel-Cologne** [comment]
Nope backend is not avilable 😂

**Comment by Marcel-Cologne** [comment]
have no acces to console ... unfortunately.

**Comment by shyim** [comment]
Go to FTP and rename var/cache/production_x to something else
