### ISSUE TITLE
Plugin composer.json has invalid "type" 

### ISSUE THREAD

**Issue by grubolsch** [FriendsOfShopware/FroshWebP#125]
### PHP Version

8.1

### Shopware Version

6.4.19.0

### Actual behaviour

When installing the plugin with composer, after plugin:refresh i get the following error

 [ERROR] The file "/var/www/lecot/shopware/custom/plugins/FroshWebP/composer.json" is invalid. Errors:
         Plugin composer.json has invalid "type" (must be "shopware-platform-plugin"), or invalid
         "extra/shopware-plugin-class" value, or missing extra.label property

### Expected behaviour

To show up as a plugin in the plugin list

### Steps to Reproduce?

composer require frosh/webp
bin/console plugin:refresh

**Comment by shyim** [comment]
That plugin is for Shopware 5 and not 6

**Comment by grubolsch** [comment]
Ah, sorry for taking your time then!
