### ISSUE TITLE
Still not two green checkmarks

### ISSUE THREAD

**Issue by mrgobby** [FriendsOfShopware/FroshWebP#126]
### Question

Hi and thanx for this great Plugin,
still a lot of work for me to do because our own Theme seems to blocks the WebP Images here and there.

My Problem:
I still have only one green checkmark at PHP GD. There is a red cross at Google cwebp. Is it absolotely neccassary to have both green checkmarks? I read that it will lead to errors when adding new pictures to the Shopware Mediamanager. 

I tried everything I found so far:
- Installing the cwebp file via the frog console command
- changing the owner of these files/dirs to the one I use for the shopware shop
- installing the Debian 11 repository cwebp files
- downloading and compiling the files directly from google (it will be installed in /usr/local/bin/)

I am not sure what the problem is. Using the cwebp command as root via ssh seems to work fine.
I am running a self hosted server with Debian 11, Apache running in froxlor. 

Maybe you can help.

Thanx 
Bastian

**Comment by shyim** [comment]
Hey,

You need only one checkmark to run this plugin :)
