### ISSUE TITLE
Add dynamic image size / Thumb Index

### ISSUE THREAD

**Issue by Hotte512** [FriendsOfShopware/FroshWebP#25]
I do have the "Problem", that Shopware does not use thumbs / image sizes in a super sense-full way.

Could we add a flexible thumb index number for Listint & Article-detail image in Plugin-Configuration?

The actual behavior on loading ArticleDetail is load ALL images size [1] for the article pictures and load all Thumbs with Index [0].
The article Picture is around 600px [1] and the thumbs are shown about 80px [0]  but loadin 200px my Listing image is about  200px and uses [0].

So atm it loads every image twice [0]200px to show with 80px and [1] as it is needed vor AricleImageSlider.

Shouldn't we switch it loading only the [1] and use it as Thumb or load Thumbs in [0] as 80px? And [1] more lazy? But then we need to use [1] in Listing ? - This would reduce requests and bytes?

Where is [2] actually in use ?

default index:
0 = 200x200
1 = 600x600
2 = 1280x1280

more sens-full:
0 = mini thump 80px
1 = Listing and slider 200px
2 = Product 600px
3 = 1280 ?

Good or bad idea? let me know :)

THX

btw. there is the prev and nex - nav without image webp atm.

**Comment by Hotte512** [comment]
may be i did not describe well what i ment with prev/next picture, it is not a theme file, these are Product images as well.

![image](https://user-images.githubusercontent.com/12100810/51769781-29f40100-20e4-11e9-9bbb-acac8022070d.png)

And I thought about adding settings for media managers thumb index options into the Plugin-config, so someone could tell webp which Index to use on detail for image.tpl and images.tpl and for listing product bos etc.

**Comment by shyim** [comment]
I have added that with prev and next to #33 
If you want dynamic image sizes look at https://github.com/FriendsOfShopware/FroshTemplateExtensions
