### ISSUE TITLE
valid license key

### ISSUE THREAD

**Issue by KaiSoellch** [FriendsOfShopware/FroshWebP#26]
Hi,

how can i get rid of these messages?
![image](https://user-images.githubusercontent.com/1941783/52051775-cd19a000-2554-11e9-987f-43cc8c8106b0.png)

Thank you in advance

Kai

**Comment by shyim** [comment]
To solve the webp plugin buy for free the plugin in store https://store.shopware.com/frosh50145464405f/webp-unterstuetzung.html

That you got a message for Optimus is a bug in Shopware License Managment. I have created a ticket already, where this should be fixed. But you can ignore it in the meanwhile
