### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by Hotte512** [FriendsOfShopware/FroshWebP#30]
## Actual behaviour

Thumbnailgenerator throws following warning:
libpng warning: iCCP: known incorrect sRGB profile
(It does not throw the image name/path)

Due to this there are some .webp images are missing, jpg seems to work.

It looks like gd can not create webp if pictures do have a "wrong" color Profile.

Maybe this can be handled with
imagepalettetotruecolor($image);
imagealphablending($image, true);
imagesavealpha($image, true);
imagewebp($im, "out.webp", 80);
???

## Expected behaviour

 webp should be generated :)

## Environment

    sw5.5.4 / webp 1.0.1 / PHP7.2.14 / gd 2.1.0 with libJPEG 6b, libPNG 1.6.28

## Steps to reproduce

1. have a picture with wrong Color-Profile 
2. php bin/console sw:thumbnail:generate -f

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

--

**Comment by shyim** [comment]
Can you provide an image with is failing?

**Comment by Hotte512** [comment]
can i find them in any log ?

![image](https://user-images.githubusercontent.com/12100810/52341579-4280e700-2a13-11e9-94ad-b6f9a61ce16d.png)

It looks like sw:thumbnail:cleanup surprised me and did remove some (original) article-pictures (jpg) there was also no webp generated, but cause the original is missing... but this can not create libpng iCCP Error.

This image are two files which disappeared after cleanup + generate https://cdn.holzundgarten.de/media/image/38/dd/08/401080_sandkasten_paula_1480x1256.jpg
https://cdn.holzundgarten.de/media/image/5d/dd/d7/SW10142_hangelleiter.jpg
but I think this might not be the files with the Color-Profile-Problem.

I'll setup a new test-system and find one, after fixing the cleanup mess...

**Comment by shyim** [comment]
I cant reproduce it with your given images 🙈

**Comment by blockberd** [comment]
I have quite a few errors like that. If you could add the filename which causes this warning, I could run the generation again and provide you with these files.
Same with the error "libpng warning: iCCP: cHRM chunk does not match sRGB" and other libpng warnings.

![grafik](https://user-images.githubusercontent.com/10122146/215799799-bf1c7cb2-0870-45f5-bccb-510c74fbba61.png)
