### ISSUE TITLE
what to do with the google binaries?

### ISSUE THREAD

**Issue by SandyMental** [FriendsOfShopware/FroshWebP#36]
Our webhoster cant compile/does not support php gd with webp  (yet).
What to do with  frosh:webp:download-google-binaries then? Yeah it downloads the binaries, but that does not change anything. frosh:webp:status still gives "[ERROR] Webp is not available"

Am I doing anything wrong? Any other issues I'm not aware of? Honestly said, I'm autodidact aka bloody amateur, so please bear that in mind when throwing any technical stuff in my direction :-)

Thanks in advance

**Comment by shyim** [comment]
Can you try to execute the binary by yourself?
./var/libwebp/bin/cwebp

**Comment by SandyMental** [comment]
wow you are super fast!

```
(22:28:36) [bin] ./cwebp
-bash: ./cwebp: No such file or directory 
```

**Comment by shyim** [comment]
Which distribution are you using?

**Comment by SandyMental** [comment]
```
Gentoo Base System release 2.3
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

```

**Comment by shyim** [comment]
Alternativly install https://packages.gentoo.org/packages/media-libs/libwebp

**Comment by SandyMental** [comment]
thanks for the hint - that favour I have to ask the server admin.
I'll get back on that as soon this is done.

good night!

**Comment by SandyMental** [comment]
> Alternativly install https://packages.gentoo.org/packages/media-libs/libwebp

sadly for whatever reasons this is not possible yet over here. in a mid term time frame it'll be possible. i have to wait.
thanks for the input!
