### ISSUE TITLE
Support for generation of specific albums (like sw:thumbnail:generate)

### ISSUE THREAD

**Issue by larsbo** [FriendsOfShopware/FroshWebP#41]

**Comment by SandyMental** [comment]
The question might sound dumb: But how would the acutal command  look like for a specific albumid?

**Comment by shyim** [comment]
frosh:webp:generate -c [albumId]

**Comment by SandyMental** [comment]
ok tried that before, but albumid like "-3" wont work?! or just stupid over here.

anyways, i let it run through on all.
