### ISSUE TITLE
Google cwebp is not always accessible although downloaded

### ISSUE THREAD

**Issue by JoshuaBehrens** [FriendsOfShopware/FroshWebP#46]
## Actual behaviour

Webserver has no webp-support using google cwebp (therefore the media manager does not convert on upload)
CLI has webp-support using google cwebp

## Expected behaviour

CLI and webserver have webp-support using google cwebp

## Environment

* Server: Plesk + Cloudlinux
* PHP 7.2

## Steps to reproduce

1. Have configured php option `open_basedir` for php-fcgi to reduce access rights
2. The symfony finder component uses different directories to search
3. Snap

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
I don't see here any potential to fix that inside the Plugin. Feel free to reopen when you have a Fix or working configuration for that Plesk + Cloudlinux mixup.
