### ISSUE TITLE
File not fouond at path

### ISSUE THREAD

**Issue by kwebKB** [FriendsOfShopware/FroshWebP#48]
Hi there, I really would like to use your plugin but im getting error messages - for example:

` 0/519 [>---------------------------]   0%media/image/s_balsam.jpg => File not                                                                    found at path: media/image/5c/e6/8d/s_balsam.jpg
   1/519 [>---------------------------]   0%media/image/s_balsam52fcc50218691.jp                                                                   g => File not found at path: media/image/14/fb/e8/s_balsam52fcc50218691.jpg
   2/519 [>---------------------------]   0%media/image/kamillen_balsam.jpg => F                                                                   ile not found at path: media/image/4a/e6/47/kamillen_balsam.jpg
   3/519 [>---------------------------]   0%media/image/kamillen_balsam52fcc5024                                                                   ae0a.jpg => File not found at path: media/image/fa/53/86/kamillen_balsam52fcc502                                                                   4ae0a.jpg
   4/519 [>---------------------------]   0%media/image/tn_ringelblumen_balsam.j                                                                   pg => File not found at path: media/image/18/5d/32/tn_ringelblumen_balsam.jpg
   5/519 [>---------------------------]   0%media/image/tn_ringelblumen_balsam52                                                                   fcc50267f08.jpg => File not found at path: media/image/d7/91/53/tn_ringelblumen_                                                                   balsam52fcc50267f08.jpg
   6/519 [>---------------------------]   1%media/image/tn_ringelblumen_balsam52                                                                   fcc502cc465.jpg => File not found at path: media/image/7a/36/90/tn_ringelblumen_                                                                   balsam52fcc502cc465.jpg
`
At the very end I´m getting error message:

`72%PHP Fatal error:  Allowed memory siz                                                                   e of 134217728 bytes exhausted (tried to allocate 47878100 bytes) in /www/htdocs                                                                   /w00f2b53/shop_neu/sw5/custom/plugins/FroshWebP/Services/WebpEncoders/PhpGd.php                                                                    on line 23
`
When I activate the plugin and the webp pictures I dont see any picture in frontend any more. Can you help me out with this?

kwebKB
Shopware 5.4.6 - latest plugin version.

**Comment by shyim** [comment]
Just increase memory limit on cli. That should do the trick
