### ISSUE TITLE
Support webp retina quality

### ISSUE THREAD

**Issue by xf-** [FriendsOfShopware/FroshWebP#52]
## Actual behaviour

One quality setting for 1x and Retina 2x

## Expected behaviour

Same as media manager - seperate settings.

## Steps to reproduce

1. Compare settings options

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Can be already defined using media manager. The plugin config is only for Main Image webp
