### ISSUE TITLE
Makes black background WebP from transparent PNG

### ISSUE THREAD

**Issue by dewib77** [FriendsOfShopware/FroshWebP#55]
## Actual behaviour

    Generating WebP pictures from my transparent PNGs makes non-transparent WebP images with black background

    Example: This PNG https://oberland.la/media/image/c9/33/bd/everbodys-darling-depp_lea_schwarz_600x600.png becomes this WebP https://oberland.la/media/image/65/e1/06/everbodys-darling-depp_lea_schwarz_600x600.webp

## Expected behaviour

    create transparent WebP from transparent PNG

## Environment

    Shopware 5.5.10 running on PHP 7.2 wiht Google cwebp an PHP GD installed

## Checklist

- [X] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [X] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Did u used PHP GD or WebP?

**Comment by dewib77** [comment]
Not sure, WebP I Think. Started the process with this command frosh:webp:generate

**Comment by shyim** [comment]
Can you execute frosh:webp:status on cli and show the result?

**Comment by dewib77** [comment]
result is: "[OK] Webp is available"

**Comment by shyim** [comment]
Using PHP GD and cwebp both looks the generated picture good for me.

Would it be possible to get access to the system to debug that?

**Comment by dewib77** [comment]
Ok. How share access data confidentially (not on Github)?

**Comment by shyim** [comment]
You can email me
s.sayakci[at]shopware.com

**Comment by cm-springlane** [comment]
We have the same problem, could you find a resolution?

**Comment by shyim** [comment]
Didn't get any image where i can reproduce that 😢

**Comment by cm-springlane** [comment]
Oooh we have lots... Let me see if I can reproduce on our staging server and give you access.

**Comment by cm-springlane** [comment]
Hi shyim, I have reproduced it on our staging system. Should I connect you with our sysadmin for getting you access or can you use the shopware access that already exists?

**Comment by cm-springlane** [comment]
Feel free to email me directly at cm-github-froshwebp@sp47.de

**Comment by thotzl** [comment]
had same issue - updating my libwebp package worked for me

**Comment by shyim** [comment]
Do you know maybe the Version Number? So I can include an version check

**Comment by thotzl** [comment]
> Do you know maybe the Version Number? So I can include an version check

Sorry, it's been a while. I can't remember exactly. I googled a bit and found this on Wikipedia: 

- "On 18 November 2011, Google began to experiment with lossless compression and support for transparency (alpha channel) in both lossless and lossy modes; support has been enabled by default in libwebp 0.2.0 (16 August 2012)."

- and this in the google sources:
https://chromium.googlesource.com/webm/libwebp/+/46e18c0a256c486cfd5360f556a90a5f6463c4d9/NEWS

- and in a different github project:
https://github.com/thumbor/thumbor/issues/501#issuecomment-117327734

I guess it would be enough to test on version > 0.4.2

**Comment by shyim** [comment]
Thanks
