### ISSUE TITLE
Doesn't work with Lazy Loading plugin

### ISSUE THREAD

**Issue by dewib77** [FriendsOfShopware/FroshWebP#56]
## Actual behaviour

    WebP images aren't used if this Lazy Loading plugin is active: https://store.shopware.com/ies6685271780164/lazy-loading.html

## Expected behaviour

    WebP to be used also in combination with the lazy loading feature

## Environment

    Shopware 5.5.10, Lazy Loading plugin ver. 5.3.1, PHP 7.2

## Checklist

- [X] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [X] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Maybe look at https://github.com/FriendsOfShopware/FroshWebP/pull/16. I don't want to add ads to a another Plugin.
Also lazy loading can handle chrome native, so there is no magic things more needed
