### ISSUE TITLE
5.6.3: Google cwebp not available -> systeminfo

### ISSUE THREAD

**Issue by ace16vitamine** [FriendsOfShopware/FroshWebP#57]
Hello, 

after successful installation cwebp is not available in Shopware -> Systeminfo ->Webpsupport.

Installation was successfu and cwebp exist: 
[root@www2 html]# ./bin/console frosh:webp:download-google-binaries
[OK] Successfully installed cwebp to /var/www/domain/html/var/libwebp/bin/cwebp

**Comment by DanMan** [comment]
Same here. `./bin/console frosh:webp:status` says "[OK] Webp is available" though.

**Comment by shyim** [comment]
That means then that cli php is able to execute the binary but fpm php not.
You should check the php configuration like disabled functions or open_basedir

**Comment by DanMan** [comment]
I'm using Plesk which manages and uses its own PHP installations, not the one the OS brings. I suppose you don't support that? I mean, it seems to work (it doesn't throw errors when generating the thumbs), only the status in the Systeminfo tab appears to be broken.

**Comment by ace16vitamine** [comment]
it is working. We have only the error in Shopware backend GUI, images are generated with .webp viewable with chrome

**Comment by shyim** [comment]
I don't have a Webspace using Plesk. So I cannot test it there.  THe backend gui is working
![Screenshot from 2019-12-13 11-03-42](https://user-images.githubusercontent.com/6224096/70791868-43ec1000-1d98-11ea-8972-dd10c4a78fb1.png)

**Comment by JoshuaBehrens** [comment]
I guess this one can be closed and linked to the existing ticket? https://github.com/FriendsOfShopware/FroshWebP/issues/46

**Comment by DanMan** [comment]
Well, the weird thing is that I've `cwebp` installed both in the OS and downloaded via console, but the plugin status still thinks it's not available.

**Comment by JoshuaBehrens** [comment]
PHP is not allowed to find it. This can be solved by adding the path to the open_basedir as @shyim stated.

**Comment by shyim** [comment]
Tested it with newest Plesk Obisidan in default settings. Its working out of the box with the binary.

**Comment by JoshuaBehrens** [comment]
In a web request?

**Comment by shyim** [comment]
Yes

**Comment by DanMan** [comment]
> Tested it with newest Plesk Obisidan in default settings. Its working out of the box with the binary.

Have you actually used it to set up a webspace and are you using its own PHP installation and not the one the OS provides? Because that's the whole point of using Plesk: so you're independent.

**Comment by shyim** [comment]
I did install an empty Debian and just run the plesk installer, created a webspace and so on

**Comment by shyim** [comment]
I will close this Issue then, cause its server configuration

**Comment by DanMan** [comment]
Ok, so I identified my issue. The cwebp executable was downloaded by a different user than the one running the PHP process through Plesk. So Shopware didn't have the right to execute it. Giving it the appropriate rights made the status page show WebP as available.

You might want to add a permission check/warning somewhere in there.
