### ISSUE TITLE
Plugin overwrites theme thumbnail setting of box-big-image.tpl

### ISSUE THREAD

**Issue by smittreiter** [FriendsOfShopware/FroshWebP#58]
If you use customer thumbnail settings webp plugin overwrites it.

In custom/plugins/FroshWebP/Resources/views/frontend/listing/product-box/box-big-image.tpl {$sArticle.image.thumbnails[1].sourceSet} is set. This overwrites custom theme settings like {$sArticle.image.thumbnails[5].sourceSet}

It would be helpfull if blocks integrated in webp plugin, so that tpl settings can be overwritten.

**Comment by shyim** [comment]
You can override the same blocks again in your Theme / plugin
