### ISSUE TITLE
HTML remains unchanged

### ISSUE THREAD

**Issue by DanMan** [FriendsOfShopware/FroshWebP#59]
## Actual behaviour

HTML is not changed, but (some?) WebP images are generated (present in `media/image` folders). But it seems like only for the base images, not the thumbnails with the dimension suffix (e.g. `200x200` and thelike).

The status page thinks there are no WebP encoders, but encoding actually works on the command line (status there is "OK" as well).

## Expected behaviour

All WebP images should be created and the generated HTML should include the WebP images instead of PNG ones.

## Environment

   Shopware 5.6.3
   Plugin 1.1.0 and Google Binary only
   PHP 7.2.27
   Webspace configured via Plesk Obsidian 18.0.21

## Steps to reproduce

1. Install plugin as documented
2. Load any frontend page like the product listing
3. Check HTML and see no mention of WebP images

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Did you enabled webp in the plugin config?

**Comment by DanMan** [comment]
Yes, I have.

**Comment by DanMan** [comment]
Another thing: when running `frosh:webp:generate` it only counts as much images as "stack" as there are in the media manager. Shouldn't the number be larger due to the thumbnails generated by `sw:thumbnail:generate`?

**Comment by DanMan** [comment]
Ok, so it kinda works, if I copy the plugin's `product-image.tpl` into my own template and re-compile the it. But even then, not nearly all images are showing up. Most are broken.

**Comment by shyim** [comment]
```frosh:webp:generate``` Just generates the images for the normal image. That's the reason why ``./bin/console sw:thumbnail:generate -f`` is required.

Did you done both commands?
Have you something special configured in your theme?

**Comment by DanMan** [comment]
Well, that's not what the installation instruction says, which is to run `sw:thumbnail:generate` first, then `frosh:webp:generate`. I've now run the former again, and now it seems to work.

But it also tried to convert the SVG files, which failed. We use one for the site logo, and that one's missing now. The generated HTML has changed and refers to a WebP image that doesn't exist. 

Strangely, the browser doesn't fall back on the also referenced SVG file in the HTML but insists to show the broken WebP file instead. What gives?

**Comment by shyim** [comment]
PHP cannot handle svg ad Image. WebP should be  ignored on svg

**Comment by DanMan** [comment]
> PHP cannot handle svg ad Image. WebP should be ignored on svg

But as I said, it isn't. The logo display is now broken. It should just leave SVGs alone.

**Comment by DanMan** [comment]
I've just tried it again with some banners, and it wasn't enough to run `frosh:webp:generate` first and then `sw:thumbnail:generate`. I had to use the force flag for the latter to have the new images show up.

That's ok for small albums like the one for banners, since you can pass the albumId as parameter. But if the product images change (new products added) and you must force re-generating all of them not just the new ones, it can take hours during which at least some images will be broken on the website.

Why is it that `sw:thumbnail:generate` doesn't pick up on the new images, if you don't force it?
