### ISSUE TITLE
Vector images broken with plugin active

### ISSUE THREAD

**Issue by DanMan** [FriendsOfShopware/FroshWebP#62]
This is a follow up to #59, so all the preconditions are the same.

We are using a SVG image for the logo. Right now the plugin tries to convert those images, too, which fails and leads to a broken image in the browser. They don't seem to try the SVG among the sources, if the WebP image fails to load.

The plugin should just leave vector images alone. It doesn't make sense to try to convert them anyway.

**Comment by shyim** [comment]
Can you test the attachment commit?

**Comment by DanMan** [comment]
Yup, logo shows up again. Thanks.

It lists the same SVG in 3 `<source>` elements, which is silly, but that might just be Shopware itself doing that.
