### ISSUE TITLE
More efficient thumbnail generation

### ISSUE THREAD

**Issue by DanMan** [FriendsOfShopware/FroshWebP#65]
You currently need to run `sw:thumbnail:generate -f` whenever an image changes. In one of our shops that takes almost 5h to finish.

There should be a way to run the thumbnail generation only for the changed images. Maybe `frosh:webp:generate` should trigger the thumbnail process, too, since it knows which images are new.

**Comment by shyim** [comment]
You only need it to run once. The webp images are generated when you upload the image. Just like the others

**Comment by DanMan** [comment]
Then there's a bug here. WebP images are not generated unless I execute the CLI command. 

Probably because of my old problem that the Plugin doesn't detect that WebP support is available (system info status page says no, CLI status says yes).

**Comment by DanMan** [comment]
Ok, so I found the issue. The cwebp executable was downloaded by a different user than the one running the PHP process through Plesk. So Shopware didn't have the right to execute it. Giving it the appropriate rights made the status page show WebP as available.

You might want to add a permission check/warning somewhere in there.

**Comment by DanMan** [comment]
See #57
