### ISSUE TITLE
Plugin tries to convert SVG images.

### ISSUE THREAD

**Issue by jhit** [FriendsOfShopware/FroshWebP#66]
## Actual behaviour

If you have SVG images in the mediamanager the plugin tries to convert the image and adds webp thumbnails to the image object.
The template then puts those broken webp links in the <picture> tag and the browser shows a broken image.

## Expected behaviour

Do not handle SVG (vector) image types.

## Environment

PHP 7.3, Shopware 5.6.6, Latest Plugin version

## Steps to reproduce

1. upload SVG to media manager
2. use it somewhere on the site
3. check for brokem image.

## Checklist

- [ x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ x] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Can you try the master branch?

**Comment by DanMan** [comment]
https://github.com/FriendsOfShopware/FroshWebP/issues/62

**Comment by jhit** [comment]
@DanMan I searched the issues for "svg" no result for #62.
@shyim Thanks, master branch fixes my issue. Closing.
