### ISSUE TITLE
Shopware 6 Support

### ISSUE THREAD

**Issue by Buzkar** [FriendsOfShopware/FroshWebP#72]
Hello,

since there is no support via the Shopware Account for this free plugin, we just wanted to ask, when it's going to be released for Shopware 6?
In the Plugin-Store is a Releasedate for march, so it's already may.
Could you please give an information about the Shopware 6 Version?

Kind Regrads
Marc Grimm

**Comment by shyim** [comment]
See https://github.com/FriendsOfShopware/FroshPlatformWebP for Shopware 6
