### ISSUE TITLE
Error in our Shop hildegard-spezialist.de

### ISSUE THREAD

**Issue by FelixOppermann555** [FriendsOfShopware/FroshWebP#73]
Hello

## Actual behaviour

Once again we have this error on the finish page on https://hildegard-spezialist.de/

CRITICAL
Message:directory '/home/gutsmiedl/htdocs/custom/plugins/FroshWebP/Resources/views/frontend/index/index.tpl' not allowed by security setting
Time:2020-09-18T11:07:43.767592+0200
Channel:core
request:
{
    "uri": "/checkout/finish",
    "method": "POST",
    "query": {
        "module": "frontend",
        "controller": "checkout",
        "action": "finish"
    },
    "post": {
        "sComment": "",
        "sAGB": "on",
        "__csrf_token": "Auio52xUva5XGBvEJpIU71FRyasUXD"
    }
}
session:No session data available
shopId:1
shopName:Deutsch

## Expected behaviour

Maybe you can solve it?

## Environment

WebP Version 1.1.0
Shopware 5.6.6
PHP Version 7.2.33
nginx/1.18.0

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
This issue can only happen when the plugin setting for showing WebP images are changed but not the cache is cleared.
