### ISSUE TITLE
Image missing / 404

### ISSUE THREAD

**Issue by Weinliebhaber** [FriendsOfShopware/FroshWebP#80]
The images can not be found on the server.

Request URL: https://www.xyz.de/media/image/93/6d/13/111295_Product_600x600@2x.webp
Request Method: GET
Status Code: 404 
Remote Address: 92.204.33.6:443
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-store, no-cache, must-revalidate, no-cache, private
content-length: 0
content-type: text/html; charset=UTF-8
date: Fri, 29 Jan 2021 09:16:47 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: nginx
set-cookie: session-1=ed0e9c9a21cb1448d23134b93987588afff7a19972e67117253f8693f8f91b62; path=/; secure; HttpOnly
x-frame-options: SAMEORIGIN
:authority: www.xyz.de
:method: GET
:path: /media/image/93/6d/13/111295_Product_600x600@2x.webp
:scheme: https
accept: image/avif,image/webp,image/apng,image/*,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
cookie: allowCookie=1; cookiePreferences={"groups":{"technical":{"name":"technical","cookies":{"cookieDeclined":{"name":"cookieDeclined","active":true},"allowCookie":{"name":"allowCookie","active":true},"shop":{"name":"shop","active":true},"csrf_token":{"name":"csrf_token","active":true},"cookiePreferences":{"name":"cookiePreferences","active":true},"x-cache-context-hash":{"name":"x-cache-context-hash","active":true},"slt":{"name":"slt","active":true},"nocache":{"name":"nocache","active":true},"session":{"name":"session","active":true},"currency":{"name":"currency","active":true}},"active":true},"comfort":{"name":"comfort","cookies":{"sUniqueID":{"name":"sUniqueID","active":true}},"active":false},"statistics":{"name":"statistics","cookies":{"adcell":{"name":"adcell","active":true},"x-ua-device":{"name":"x-ua-device","active":true},"mmFacebookPixel":{"name":"mmFacebookPixel","active":true},"biloba_google_gtagjs":{"name":"biloba_google_gtagjs","active":true},"matomo":{"name":"matomo","active":true},"lenzBingAdsConversionTracking":{"name":"lenzBingAdsConversionTracking","active":true},"partner":{"name":"partner","active":true}},"active":false}},"hash":"WyJhZGNlbGwiLCJhbGxvd0Nvb2tpZSIsImJpbG9iYV9nb29nbGVfZ3RhZ2pzIiwiY29tZm9ydCIsImNvb2tpZURlY2xpbmVkIiwiY29va2llUHJlZmVyZW5jZXMiLCJjc3JmX3Rva2VuIiwiY3VycmVuY3kiLCJsZW56QmluZ0Fkc0NvbnZlcnNpb25UcmFja2luZyIsIm1hdG9tbyIsIm1tRmFjZWJvb2tQaXhlbCIsIm5vY2FjaGUiLCJwYXJ0bmVyIiwic1VuaXF1ZUlEIiwic2Vzc2lvbiIsInNob3AiLCJzbHQiLCJzdGF0aXN0aWNzIiwidGVjaG5pY2FsIiwieC1jYWNoZS1jb250ZXh0LWhhc2giLCJ4LXVhLWRldmljZSJd"}; _ga=GA1.2.54235383.1610990152; _fbp=fb.1.1610990152139.1014963417; session-1=ed0e9c9a21cb1448d23134b93987588afff7a19972e67117253f8693f8f91b62; __csrf_token-1=JlYEn05JVhMYnldjKFVCMhNZUgGYL6; _gid=GA1.2.565437212.1611576216; nocache=detail-1; _gat_gtag_UA_53703219_1=1; x-ua-device=desktop; _uetsid=5a38eea05f0511ebae9d83cf996ed9a0; _uetvid=d17406a059b011ebad4485f0c74ac11f
referer: https://www.xyz.de/kellerei-kaltern-castel-giovanelli-sauvignon-doc-2014
sec-fetch-dest: image
sec-fetch-mode: no-cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36

**Comment by shyim** [comment]
Did you done the Installation Manuel? https://github.com/FriendsOfShopware/FroshWebP/blob/master/Resources/store/de_manual.md

**Comment by Weinliebhaber** [comment]
That has been the missing part. Thank you very much!
