### ISSUE TITLE
WebP & BSP Spin: Premium 360 Grad

### ISSUE THREAD

**Issue by xp24** [FriendsOfShopware/FroshWebP#83]
# Prerequisites

## Actual behaviour

When using the "BSP Spin: Premium 360 Grad" plug-in in conjunction with the WebP plug-in, the phenomenon occurs that the 360 ° view of the 360 ° plug-in is not loaded in the image gallery - modal box. I think it has to do with the fact that the "swImageGallery" function is overwritten and the JS of the "BSP Spin: Premium 360 Grad" plugin cannot work?

Beim Einsatz des Plugins "BSP Spin: Premium 360 Grad" in Verbindung mit dem WebP Plugin, kommt es zu dem Phänomen, das in der image-gallery--modal Box die 360° Ansicht des 360° plugins nicht geladen wird. Ich denke es hängt damit zusammen das die Funktion "swImageGallery" überschrieben wird und das JS des Plugins "BSP Spin: Premium 360 Grad" nicht greifen kann?

## Expected behaviour

I would like the other plugins, especially the "BSP Spin: Premium 360 Grad" plugin to work with your plugin.
    Ich würde mir wünschen das andere Plugins, im speziellen das Plugin "BSP Spin: Premium 360 Grad" mit eurem plugin funktioniert.

## Environment

    PHP 7.3.27, SW 5.6.9

## Steps to reproduce

1. install clean SW with Testproducts
2. install Testversion Plugin "BSP Spin: Premium 360 Grad" and test the correct function on a article
3. install FROSH WebP and test the correct function on the same article

## Checklist

- [x] I am using the latest stable version of this plugin.

--

**Comment by shyim** [comment]
Hey,

leider kann die Storefront in Shopware keine mehrfach Überschreibungen von Javascripten vom selben JS Plugin. Der einfachste Fix wäre wenn du im Theme es erneut überschreibst und sozusagen beides (die Überschreibungen von hier und des WebP Plugins) in deiner Datei drin hast.

**Comment by xp24** [comment]
Danke dir!
