### ISSUE TITLE
Not creating WebP Pictures

### ISSUE THREAD

**Issue by Weinliebhaber** [FriendsOfShopware/FroshWebP#84]
Hello,

after installing the plugin, we did as described in the manual. Every available picture has been converted into WebP. Pictures that have been uploaded afterwards will not be converted.

Thank you
Oliver

**Comment by shyim** [comment]
How did you uploaded it?

**Comment by Weinliebhaber** [comment]
With the media manager and it took really long. Five PNG, not cropped, 3,44MB took about 2 mins to upload.

**Comment by shyim** [comment]
Can you make an screenshot of systeminfo -> webp?

**Comment by Weinliebhaber** [comment]
Sure...there you go.d

![image](https://user-images.githubusercontent.com/78203440/110118961-6a420500-7dbb-11eb-8a9f-0e51aa69450c.png)

**Comment by Weinliebhaber** [comment]
Hello...is that the reason?

**Comment by Weinliebhaber** [comment]
Installed cwebp but still not converting to webp.

![image](https://user-images.githubusercontent.com/78203440/110476270-13516e00-80e2-11eb-86de-d35b45e55079.png)

**Comment by shyim** [comment]
I don't know needs more debugging why its not called

**Comment by Weinliebhaber** [comment]
Where do you want me to debug. I can start the console while uploading. Would that help?

**Comment by shyim** [comment]
Is this problem still there?

**Comment by Weinliebhaber** [comment]
Hello,

it´s working now, but to be honest we don´t know why. We´ve installed everything like in your tutorial and it still didn´t work. So we kept go on generating the webp pictures manually. After a few weeks it worked automatically. 

Than you for coming back to me....

**Comment by shyim** [comment]
Thanks for the info :)
