### ISSUE TITLE
Show thumbnails in the backend

### ISSUE THREAD

**Issue by magnolia4** [FriendsOfShopware/FroshWebP#85]
It would be great if the thumbnails were also visible in the backend in the media management on the image:

![image](https://user-images.githubusercontent.com/9446008/111294057-392ec380-864a-11eb-80f2-8323452a86cd.png)

**Comment by shyim** [comment]
Hey,

we concentrate only on Shopware 6 plugins. Feel free to create an Pull request when you want to implement it by own 😊
