### ISSUE TITLE
Support for older Browsers

### ISSUE THREAD

**Issue by m-aus-b** [FriendsOfShopware/FroshWebP#87]
The Plugin does a great job, but in older Browsers like Safari 13 or IE 11 are no images available. 

It would be great, if a fallback to the jpg/png media would be included.

**Comment by shyim** [comment]
The fallback is included 🤔

**Comment by m-aus-b** [comment]
I have seen something like this in the template, but the convert-command converts all jpg/png to WebP and the original images will be replaced.

**Comment by shyim** [comment]
The original images stay there. It just created an new file with the same name and changes the extension to webp. All places there webp is used has an picture tag to ensure the image is loaded only when webp is there. 

Which page does break?

**Comment by m-aus-b** [comment]
The problem was, that the images were original uploaded as WEBP. In this case the fallback can´t work. Thanks for the fast support and sorry. 
The fallback works fine, if the image is original PNG/JPG.
