### ISSUE TITLE
Keine Umwandlung bei Bilder Upload via API 

### ISSUE THREAD

**Issue by bttfw** [FriendsOfShopware/FroshWebP#91]
Ich gehe jetzt Mal davon aus das die Bilder nicht umgewandelt werden bei dem Upload via API.

Wenn ich jetzt nach dem Upload per Commando Zeile die Umwandlung Trigger werden dann nur die neuen Bilder umgewandelt oder wieder alle ?

Und ist es nötig die Thumbnails vorher neu zu generieren?

**Comment by shyim** [comment]
Hey,

die Bilder werden auch via API generiert. Der Cli befehl ist nur einmal nötig
