### ISSUE TITLE
WebP for CSS background-image property and HTML img tags of custom code elements

### ISSUE THREAD

**Issue by IMolterer** [FriendsOfShopware/FroshWebP#92]
Currently the plugin is working as expected, but not for the CSS background-image property and the HTML img tags in custom code elements.
Is there a way to add this functionality?

-------------------------------------------

Derzeit funktioniert das Plugin wie erwartet, aber nicht für die CSS background-image-Eigenschaft und die HTML-img-Tags in Custom Code-Elementen.
Gibt es eine Möglichkeit, diese Funktionalität hinzuzufügen?

**Comment by DeubaIT** [comment]
I have to add to the request the following elements, that are not supportet:
- category-listing 
- slider-elements like manufacturer, emotion, and thumbnail slider on product detail page (element with class="image-slider--thumbnails-slide")

**Comment by shyim** [comment]
I have no clue how to do that automatically in custom elements. If you have an idea of how to solve it. let me know

**Comment by shyim** [comment]
When you want to deliver a webp image. You need to create the picture element by own in the custom code element. The URL is the same but with webp extension

**Comment by IMolterer** [comment]
Thanks a lot for you help, I will try your suggestions!
