### ISSUE TITLE
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by Gruenbaer** [FriendsOfShopware/FroshWebP#93]
Hello!
It appears that the images are all in webp format now, but due to the large amount it is impossible to check all of them.
I am clueless on how to resolve this error and am hoping for your help.

## Actual behaviour
Here is the complete output in the shell:
`
 ./bin/console frosh:webp:generate
STACK: 29594
OFFSET: 0
 29007/29594 [===========================>]  98%libpng warning: iCCP: known inco                      rrect sRGB profile
 29594/29594 [============================] 100%
In DBALException.php line 179:

  An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.albumID AS albumID_1, s0_.name AS name_2, s0_.description AS description_3, s0_.path AS path_4, s0_.type AS type_5, s0_.extension AS extension_6, s0_.userID AS userID_7, s0_.created AS created_8, s0_.file_size AS file_size_9, s0_.width AS width_10, s0_.height AS height_11 FROM s_media s0_ WHERE s0_.type = ?
  AND s0_.albumID <> -13 LIMIT 29594 OFFSET 29594' with params ["IMAGE"]:

  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

In Connection.php line 907:
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

frosh:webp:generate [-s|--stack [STACK]] [-o|--offset [OFFSET]] [-f|--force [FORCE]] [-c|--setCollection [SETCOLLECTION]] [-i|--ignoreCollection [IGNORECOLLECTION]]

`
## Expected behaviour

    The error not to appear :)

## Environment

    Mittwald mServer
    Shopware 5.6.9
    7.3-latest FPM

## Steps to reproduce

1. Just run the command and wait a couple of hours.

## Checklist

- [x ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Can you add here
https://github.com/FriendsOfShopware/FroshWebP/blob/master/Commands/GenerateWebpImages.php#L128

```$this->modelManager->getConnection()->executeQuery('SELECT 1');```
