### ISSUE TITLE
Images missing in Emotion Slider

### ISSUE THREAD

**Issue by romanWienicke** [FriendsOfShopware/FroshWebP#94]
## Actual behaviour

      when the plugin is activated the "banner slider" within the shopping worlds is loosing its images

## Expected behaviour

    the images should be still there

## Environment

    Shopware 5.6.9, Frosh WebP Plugin 1.1.2

## Steps to reproduce

1. Create a shopping world
2. add a banner slider with 2 or more images
3. activate the WebP plugin
4. the images inside the slider disappear
5. deactivate the WebP plugin
6. the images are there as expected

## Checklist

- [ x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshWebP/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ x] I am using the latest stable version of this plugin.

## Code:
It seems as the slider doesn*t support the newly added picture tags:
`<div class="emotion--banner-slider image-slider" data-image-slider="true" data-thumbnails="false" data-lightbox="false" data-loopslides="true" data-animationspeed="500" data-arrowcontrols="true" data-autoslideinterval="5000" data-autoslide="true" data-imageselector=".image-slider--item">
	<div class="banner-slider--container image-slider--container">
		<div class="banner-slider--slide image-slider--slide" style="transition: all 500ms cubic-bezier(0.2, 0.89, 0.75, 0.99) 0s; transform: translateX(0%);">
			<div class="banner-slider--item image-slider--item" data-coverimage="true" data-containerselector=".banner-slider--banner" data-width="1278" data-height="720">
				<div class="banner-slider--banner" style="width: 100%; height: 1072.11px;">
					<**picture**>
						<source srcset="https://www.mysite.tld.com/media/image/8f/2a/8c/image1_800x800.webp 800w, 
							https://www.mysite.tld.com/media/image/1d/4e/46/image1_1280x1280.webp 1280w, 
							https://www.mysite.tld.com/media/image/68/e9/9c/image1_1920x1920.webp 1920w" sizes="(min-width: 78.75em) 100vw, (min-width: 64em) 100vw, (min-width: 48em) 100vw, (min-width: 30em) 100vw, 100vw" type="image/webp">
							<img loading="lazy" src="https://www.mysite.tld.com/media/image/da/dd/a6/image1_800x800.jpg" class="banner-slider--image" sizes="(min-width: 78.75em) 100vw, (min-width: 64em) 100vw, (min-width: 48em) 100vw, (min-width: 30em) 100vw, 100vw" srcset="https://www.mysite.tld.com/media/image/da/dd/a6/image1_800x800.jpg 800w, https://www.mysite.tld.com/media/image/40/ea/61/image1_1280x1280.jpg 1280w, https://www.mysite.tld.com/media/image/17/0c/15/image1_1920x1920.jpg 1920w" style="width: 100%;">
							</picture>
						</div>
					</div>
					<div class="banner-slider--item image-slider--item" data-coverimage="true" data-containerselector=".banner-slider--banner" data-width="1278" data-height="720">
						<div class="banner-slider--banner" style="width: 100%; height: 1072.11px;">
							<picture>
								<source srcset="https://www.mysite.tld.com/media/image/ab/27/d7/image2.webp 800w, https://www.mysite.tld.com/media/image/c6/d3/91/Content-Promo-Banner-Standort-Bozen_1280x1280.webp 1280w, https://www.mysite.tld.com/media/image/58/89/12/Content-Promo-Banner-Standort-Bozen_1920x1920.webp 1920w" sizes="(min-width: 78.75em) 100vw, (min-width: 64em) 100vw, (min-width: 48em) 100vw, (min-width: 30em) 100vw, 100vw" type="image/webp">
									<img loading="lazy" src="https://www.mysite.tld.com/media/image/6c/6a/b6/image2.jpg" class="banner-slider--image" sizes="(min-width: 78.75em) 100vw, (min-width: 64em) 100vw, (min-width: 48em) 100vw, (min-width: 30em) 100vw, 100vw" srcset="https://www.mysite.tld.com/media/image/6c/6a/b6/image2.jpg 800w, https://www.mysite.tld.com/media/image/31/f2/44/Content-Promo-Banner-Standort-Bozen_1280x1280.jpg 1280w, https://www.mysite.tld.com/media/image/27/0e/0e/Content-Promo-Banner-Standort-Bozen_1920x1920.jpg 1920w" style="width: 100%;">
									</picture>
								</div>
							</div>
						</div>
						<div class="image-slider--dots">
							<div class="dot--link is--active"/>
							<div class="dot--link"/>
						</div>
						<a class="force--3d arrow is--left"/>
						<a class="force--3d arrow is--right"/>
					</div>
				</div>`

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by resslinger** [comment]
I have the same error on our site.

@shyim I found a issue with the lazy loading. If a remove this tag, the image was shown.

**Comment by shyim** [comment]
Tagged an new version. https://github.com/FriendsOfShopware/FroshWebP/releases/tag/1.1.3
Should be in store in approx. 5 minutes
