### ISSUE TITLE
Webp support for standard designer elements

### ISSUE THREAD

**Issue by DeubaIT** [FriendsOfShopware/FroshWebP#96]
## Actual behaviour
No webp support for standard designer elements like 'Hersteller-Slider, 'Artikel-slider', images on category-listing pages or preview pictures on the product detatil page.

![Article_DetailPage](https://user-images.githubusercontent.com/53908029/120980221-b3b53e00-c776-11eb-9fd2-55de200a0dda.PNG)
![Category_Listing](https://user-images.githubusercontent.com/53908029/120980235-b6179800-c776-11eb-8934-8fc75f6b7173.PNG)

## Expected behaviour

Display of the images in webp format. 

## Environment 
Shopware 5.6.9,  Shopware Security Plugin 1.1.22, 
Webp Unterstützung 1.1.3
'Nicht sichtbare Bilder aufschieben / lazy loading 1.2.19 (Maxi Arnicke)'
....

## Steps to reproduce

1. https://www.deubaxxl.de/
2. https://www.deubaxxl.de/heimwerker/
3. https://www.deubaxxl.de/plattformwagen-150-kg/32/

**Comment by DeubaIT** [comment]
We would be happy to give you a short response if information on how to answer the question is missing.

**Comment by shyim** [comment]
Is the template modified? the listing product boxes should work in default :thinking:

**Comment by DeubaIT** [comment]
The only modification in listing.tpl is in one block:

{extends file='parent:frontend/listing/listing.tpl'}

{block name="frontend_listing_top_actions"}
    {include file='frontend/listing/category_cards.tpl'}
    {$smarty.block.parent}
{/block}

So e reset the changes on our test server and check whether the display is then correct.

**Comment by shyim** [comment]
Yes check it with default theme and no plugins maybe

**Comment by DeubaIT** [comment]
After a few tests there is the following result:
- webp support for the standard article slider is ok in all themes
- webp support in the category listing is ok for the shopware responsive theme and a 3rd party theme
- our theme is derived from the 3rd party theme, and here is the problem

So, how can we check, which changes causes the issues?
The only change in listing.tpl is the following:
        {block name="frontend_listing_top_actions"}
            {include file='frontend/listing/....'}
            {$smarty.block.parent}
        {/block}
We have also made changes in the product_badges.tpl.

Which template files or {block} implements the webp support?

Another problem is that we have implemented our own article slider based on an emotion-plugin example from shopware.
How can webp support be integrated into your own components?

Thanks in advance

**Comment by shyim** [comment]
All templates from the plugin are relevant for that. 

To add webp support by own create a picture tag and add a source to the webp image. https://github.com/FriendsOfShopware/FroshWebP/blob/master/Resources/views/frontend/listing/product-box/product-image.tpl#L5-L12 

That way it works for all things :)
