### ISSUE TITLE
MySQL error at the end. Plugin 1.1.4 / SW 5.6.9

### ISSUE THREAD

**Issue by HubertusMagnus** [FriendsOfShopware/FroshWebP#98]
time ./bin/console frosh:webp:generate
STACK: 5901
OFFSET: 0
   79/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   80/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   81/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   82/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   83/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   84/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   85/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   87/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   88/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   89/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
   90/5901 [>---------------------------]   1%libpng warning: iCCP: known incorrect sRGB profile
 4752/5901 [======================>-----]  80%libpng warning: iCCP: known incorrect sRGB profile
 4753/5901 [======================>-----]  80%libpng warning: iCCP: known incorrect sRGB profile
 4949/5901 [=======================>----]  83%libpng warning: iCCP: known incorrect sRGB profile
 5901/5901 [============================] 100%
In DBALException.php line 179:

  An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.albumID AS albumID_1, s0_.name AS name_2, s0_.description AS description_3, s0_.path AS path_4, s0_.type AS type_5, s0_.extension AS extension_6, s0_.userID AS userID
  _7, s0_.created AS created_8, s0_.file_size AS file_size_9, s0_.width AS width_10, s0_.height AS height_11 FROM s_media s0_ WHERE s0_.type = ? AND s0_.albumID <> -13 LIMIT 5901 OFFSET 5901' with params ["IMAGE"]:

  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

In Connection.php line 907:

  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

frosh:webp:generate [-s|--stack [STACK]] [-o|--offset [OFFSET]] [-f|--force [FORCE]] [-c|--setCollection [SETCOLLECTION]] [-i|--ignoreCollection [IGNORECOLLECTION]]

real	42m14.141s
user	37m55.290s
sys	3m53.847s

**Comment by shyim** [comment]
Can you test this fix? https://github.com/FriendsOfShopware/FroshWebP/commit/9cea42fad079c671a623f02d886e705bb9672e6b

**Comment by HubertusMagnus** [comment]
thanks,  now it runs very fast, cuz it has nothing to do:

STACK: 5947
OFFSET: 0
    0 [>---------------------------]
real	0m0.570s
user	0m0.369s
sys	0m0.116s

will test the fix on the next project.

**Comment by shyim** [comment]
Okay
