### ISSUE TITLE
The console process does not create thumbnails

### ISSUE THREAD

**Issue by clevercommerce** [FriendsOfShopware/FroshWebP#99]
### PHP Version

7.2

### Shopware Version

5.6.9

### Actual behaviour

If I use the normal frosh:webp:generate (-force) command all looks fine. It needs its time, at the end I got some sql gone away errors but I had this erros already  with no impacts.
In this new project the process doesnt create the configured thumbnails. It only creats the webp baseimage but none of the needed xxx_200x200. xxx_150x150. etc pp.

### Expected behaviour

It should create every configured thumbnail

### Steps to Reproduce?

its hard because on the most env i have tested it all was good but here:

console command 
frosh:webp:generate (-force)

=does not create any thumb.

**Comment by shyim** [comment]
the command is also not intended for that. it creates only the original commands in webp.
You need to run sw:thumbnail:generate -f

**Comment by clevercommerce** [comment]
I did it like I read in the install guide:
first use sw:thumbnail:generate -f
after this is ready I use:
frosh:webp:generate

I did that in an staging env from the same shop and it works fine at all. 
I tried that already a several times but always the same picture no thumbnails a lot of orginal webp images. So any idea where I can find or look for the issue?

thx

**Comment by shyim** [comment]
Idk You should debug here https://github.com/FriendsOfShopware/FroshWebP/blob/master/Components/Thumbnail/Generator/WebPGenerator.php#L104 it can be anything
